### ISSUE TITLE
KeyError: 'sections'

### ISSUE THREAD

**Issue by hubert3** [jordidg/mixcloud-dl#1]
$ ./mixcloud_dl.py http://www.mixcloud.com/livesetsdjmixes/tiga-6-mix-sat-08-03-2012/
INFO: Get information
Traceback (most recent call last):
  File "./mixcloud_dl.py", line 317, in <module>
    main()
  File "./mixcloud_dl.py", line 312, in main
    get_mix(url, options)
  File "./mixcloud_dl.py", line 119, in get_mix
    info = get_info(url)
  File "./mixcloud_dl.py", line 104, in get_info
    entry["sections"][0]["start_time"] = 0
KeyError: 'sections'

**Comment by buckleytom** [comment]
well, that sucks. thanks for working on this anyway, @jordidg. you might think about helping other users from trying to out only to get an error message by editing the description here to tell people about mixcloud's lockdown.
